- name: Create a k8s namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item.name }}"
    state: present
  loop: "{{ namespaces }}"
  tags: namespaces

- name: Deploy Service
  k8s:
    state: present
    template: "{{ role_path }}/../templates/service.yml.j2"
  loop: "{{ services }}"
  tags:
    - service

- name: Deploy Deployment
  k8s:
    state: present
    template: "{{ role_path }}/../templates/deployment.yml.j2"
  loop: "{{ deployments }}"
  tags:
    - deployment