- name: Install k3s server on the first node
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --tls-san {{ load_balancer_public_ip }}" sh -
  when: inventory_hostname == groups['kubernetes_workers'][0]

- name: Fetch K3S token from the first node
  shell: |
    cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  when: inventory_hostname == groups['kubernetes_workers'][0]
  delegate_to: "{{ groups['kubernetes_workers'][0] }}"
  run_once: true

- name: Install k3s server and join the cluster on other nodes
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --server https://{{ hostvars[groups['kubernetes_workers'][0]]['ansible_host'] }}:6443" K3S_TOKEN={{ k3s_token.stdout }} sh -
  when: inventory_hostname != groups['kubernetes_workers'][0]

- name: Verify k3s installation on each node
  command: kubectl get nodes
  register: k3s_output
  changed_when: false
  ignore_errors: true

- name: install pip3
  apt: 
    update_cache: yes
    pkg: 
      - python3-pip 

    state: present

- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 