# Ansible Inventory for Azure Kubernetes Cluster
# Generated by Terraform on ${timestamp()}

[all:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Container Registry Configuration
acr_name=${values(acr_name)[0]}
acr_server=${values(acr_name)[0]}.azurecr.io

[kubernetes_workers]
%{ for idx, worker in kubernetes_workers ~}
${worker.name} ansible_host=${worker.public_ip}\
%{ if worker.name != "k3s-master-1" ~} ansible_ssh_common_args='-o ProxyJump=ubuntu@${kubernetes_workers[0].public_ip}'%{ endif ~}
%{ endfor ~}

[kubernetes_nodes:children]
kubernetes_workers

# Group variables for roles
[kubernetes_install:vars]
k8s_version=1.28.0
container_runtime=containerd

[kubernetes_backend:vars]
app_type=backend
acr_name=backend

[kubernetes_frontend:vars]
app_type=frontend
acr_name=frontend
