# Ansible Inventory for Azure Kubernetes Cluster
# Generated by Terraform on ${timestamp()}

[all:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Container Registry Configuration
acr_name=${values(acr_name)[0]}
acr_server=${values(acr_name)[0]}.azurecr.io

[kubernetes_workers]
%{ for idx, worker in kubernetes_workers ~}
${worker.name} ansible_host=${worker.public_ip != "" ? worker.public_ip : worker.private_ip} 
%{ if worker.name != "k3s-master-1" ~} 
ansible_ssh_common_args='-o ProxyJump=ubuntu@${kubernetes_workers[0].public_ip}'
%{ endif ~}
%{ endfor ~}