---
namespaces: [
    {
      "name": "lab"
    }
]
configmaps: [
  {
    "name": "backend-config",
    "data": {
      DB_HOST: "my-infra-maindb-dev.postgres.database.azure.com",
      DB_PORT: "5432",
      DB_NAME: "postgres?sslmode=require",
      REDIS_HOST: "redis-svc",
      REDIS_PORT: "6379"
    },
    "namespace": "lab"
  }
]
secrets: [
  {
    "name": "backend-secret",
    "data": {
      "DB_USER": "schedule_user",
      "DB_PASSWORD": "MyPassword1234!"
    },
    "namespace": "lab"
  }
]
services: [
  {
    "name": "backend-svc",
    "app": "backend",
    "type": "NodePort",
    "port": 8080,
    "target_port": 8080,
    "protocol": "TCP",
    "node_port": 30088,
    "namespace": "lab"
  }
]
deployments:  [
  {
    "name": "backend",
    "app": "backend",
    "registry": "dockerhub",
    "image": "dolvladzio/backend",
    "replicas": 1,
    "port": 8080,
    "config_refs": ["backend-config"],
    "secret_refs": ["backend-secret"],
    "namespace": "lab"
  }
]