---
namespaces: [
    {
      "name": "lab"
    }
]
services: [
  {
    "name": "frontend-svc",
    "app": "frontend",
    "type": "NodePort",
    "port": 80,
    "target_port": 80,
    "protocol": "TCP",
    "node_port": 30080,
    "namespace": "lab"
  }
]
deployments:  [
  {
    "name": "frontend",
    "app": "frontend",
    "registry": "dockerhub",
    "image": "dolvladzio/frontend",
    "replicas": 1,
    "port": 80,
    "config_refs": [],
    "secret_refs": [],
    "namespace": "lab"
  }
]