- name: Install k3s
  hosts: kubernetes_workers
  become: yes
  roles: 
    - install_k3s

- name: K3s - frontend
  hosts: "{{ groups['kubernetes_workers'][0] }}"
  become: yes
  roles:
    - k3s_deploy-frontend