- name: Install k3s
  hosts: kubernetes_workers
  become: yes
  vars:
    master_node: k3s-master-1
  roles: 
    - install_k3s

- name: K3s - frontend
  hosts: kubernetes_workers
  become: yes
  roles: 
    - k3s_deploy-frontend
