- name: Install k3s
  hosts: kubernetes_workers
  become: yes
  roles: 
    - install_k3s

- name: K3s - frontend
  hosts: "{{ groups['kubernetes_workers'][0] }}"
  become: yes
  roles:
    - k3s_deploy-frontend

- name: K3s - redis
  hosts: "{{ groups['kubernetes_workers'][1] }}"
  become: yes
  roles:
    - k3s_deploy-redis

- name: K3s - backend
  hosts: "{{ groups['kubernetes_workers'][2] }}"
  become: yes
  roles:
    - k3s_deploy-backend

- name: K3s - ingress
  hosts: kubernetes_workers
  become: yes
  roles:
    - k3s_ingress